# Generated by Django 5.0.1 on 2024-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_gallery_image_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
